apiVersion: v1
kind: Service
metadata:
  name: notification-worker
spec:
  selector:
    app: notification-worker
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
